window_title: 冒险岛怀旧服
start_stop_hotkey: F6
reference_width: 1368
reference_height: 800
fps: 10
keyboard_mode: sendinput
confidence: 0.6
model_path: D:/GAME/mxd-automation/train/scripts/02_train_yolo/model/best.onnx
monster_classes: monster
floor_classes: floor
rope_classes: rope
player_classes: player
self_name: 东乡一二三
self_offset: 85
hp_region:
- 0.3389458272327965
- 0.9661458333333334
- 0.12298682284040996
- 0.026041666666666668
hp_color:
- 206
- 131
- 130
hp_tolerance: 20
hp_threshold: 0.5
hp_key: end
mp_region:
- 0.4633967789165447
- 0.9661458333333334
- 0.1273792093704246
- 0.032552083333333336
mp_color:
- 6
- 114
- 201
mp_tolerance: 20
mp_threshold: 0.5
mp_key: pdn
target_key: tab
jump_key: alt
attack_type: long
attack_range: 400
attack_range_y: 30
attack_min_range: 0
knockback_skill:
  name: 击退技能
  key: D
  cooldown: 0.2
  range: 120
stand_mode: false
stand_facing: right
stand_default_attack: false
stand_skill2_only: false
stand_micro_move_enabled: false
stand_micro_move_interval: 180.0
stand_micro_move_tap_ms: 30
skills:
- name: 连击
  key: a
  cooldown: 0.4
- name: 爆炸箭
  key: space
  cooldown: 0.4
buff_skills:
- name: 无形箭
  key: '2'
  cooldown: 140.0
- name: 快速箭
  key: '3'
  cooldown: 50.0
pickup_enabled: false
pickup_key: z
pickup_interval: 0.333
screenshot_interval: 60
lie_detect_enabled: true
lie_detect_template: assets/templates/lie_detector.png
lie_detect_threshold: 0.78
